version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/app/
      - /app/node_modules
    ports:
      - "8080:8080"
    networks:
      - app-network
    frontend:
      build:
        context: ./frontend
        dockerfile: ./Dockerfile
      stdin_open: true
      volumes:
        - ./frontend:/app/
        - /app/node_modules
      ports:
        - "80:3000"
      networks:
        - app-network

  #Docker Networks
  networks:
    app-network:
      driver: bridge